# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mr Dipalma's Pub üç∫
author:
  name: dpalmasan
description: >- # this means to ignore newlines until "baseurl:"
  Este es un blog donde compartir√© un poco sobre m√≠ y mis experiencias
  en el mundo tecnol√≥gico.
baseurl: "/website" # the subpath of your site, e.g. /blog
url: "https://dpalmasan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dpalmasan
github_username:  dpalmasan

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-spaceship
  - jekyll-remote-theme

port: 4002
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

google_analytics: G-KHXBX5G1VP

minima:
  skin: classic
  social_links:
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/dpalmasan/"
      title:  Mi perfil en Linkedin
    - platform: github
      user_url: "https://www.github.com/dpalmasan"
      title:  Mi Github
    - platform: google_scholar
      user_url: "https://scholar.google.com/citations?user=Y5PN_1AAAAAJ&hl=en"
      title:  Mi Google Scholar
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/4051219/dpalma"
      title:  Mis preguntas en SO LOL!

disqus:
  shortname: dpalmasan
  url: "https://dpalmasan.github.io/website/"
